//
// Created by raspberry on 2020-11-24.
//

#ifndef MARS_MISSIONS_MANAGEMENT_MARSSTATION_H
#define MARS_MISSIONS_MANAGEMENT_MARSSTATION_H


class MarsStation {

};


#endif //MARS_MISSIONS_MANAGEMENT_MARSSTATION_H
